// Function that allow to choose background color of type
export const colorTypes = {
  acero: "bg-pokemon-acero",
  agua: "bg-pokemon-agua",
  bicho: "bg-pokemon-bicho",
  dragón: "bg-pokemon-dragon",
  eléctrico: "bg-pokemon-electrico",
  fantasma: "bg-pokemon-fantasma",
  fuego: "bg-pokemon-fuego",
  hada: "bg-pokemon-hada",
  hielo: "bg-pokemon-hielo",
  lucha: "bg-pokemon-lucha",
  normal: "bg-pokemon-normal",
  planta: "bg-pokemon-planta",
  psíquico: "bg-pokemon-psiquico",
  roca: "bg-pokemon-roca",
  siniestro: "bg-pokemon-siniestro",
  tierra: "bg-pokemon-tierra",
  veneno: "bg-pokemon-veneno",
  volador: "bg-pokemon-volador",
};

// Function that allow to set the style of a game
export const gamesInfo = {
  red: { nombre: "Rojo", color: "bg-red-700", icon: "FaGamepad" },
  blue: { nombre: "Azul", color: "bg-blue-700", icon: "FaGamepad" },
  yellow: { nombre: "Amarillo", color: "bg-yellow-500", icon: "FaGamepad" },
  gold: { nombre: "Oro", color: "bg-yellow-500", icon: "FaGamepad" },
  silver: { nombre: "Plata", color: "bg-gray-400", icon: "FaGamepad" },
  crystal: { nombre: "Cristal", color: "bg-blue-500", icon: "FaGamepad" },
  ruby: { nombre: "Rubí", color: "bg-red-400", icon: "SiNintendo" },
  sapphire: { nombre: "Zafiro", color: "bg-blue-500", icon: "SiNintendo" },
  emerald: { nombre: "Esmeralda", color: "bg-green-600", icon: "SiNintendo" },
  firered: { nombre: "Fuego Rojo", color: "bg-red-700", icon: "SiNintendo" },
  leafgreen: {
    nombre: "Hoja Verde",
    color: "bg-green-600",
    icon: "SiNintendo",
  },
  diamond: {
    nombre: "Diamante",
    color: "bg-blue-600",
    icon: "SiNintendo3Ds",
  },
  pearl: { nombre: "Perla", color: "bg-blue-500", icon: "SiNintendo3Ds" },
  platinum: {
    nombre: "Platino",
    color: "bg-gray-600",
    icon: "SiNintendo3Ds",
  },
  heartgold: {
    nombre: "Heart Gold",
    color: "bg-yellow-500",
    icon: "SiNintendo3Ds",
  },
  soulsilver: {
    nombre: "Soul Silver",
    color: "bg-gray-600",
    icon: "SiNintendo3Ds",
  },
  black: { nombre: "Negro", color: "bg-black", icon: "SiNintendo3Ds" },
  white: {
    nombre: "Blanco",
    color: "bg-white",
    text: "text-black",
    icon: "SiNintendo3Ds",
  },
  "black-2": { nombre: "Negro 2", color: "bg-black", icon: "SiNintendo3Ds" },
  "white-2": {
    nombre: "Blanco 2",
    color: "bg-white",
    text: "text-black",
    icon: "SiNintendo3Ds",
  },
};
